[package]
name = "rustcast"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
applications = "0.3.1"
global-hotkey = "0.7.0"
iced = { version = "0.14.0", features = ["image", "smol", "tokio"] }
icns = "0.3.1"
image = "0.25.9"
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-application-services = { version = "0.3.2", default-features = false, features = [
    "HIServices",
    "Processes",
] }
objc2-foundation = "0.3.2"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"

[package.metadata.bundle]
name = "RustCast"
identifier = "com.umangsurana.rustcast"
icon = ["bundling/icon.icns"]
version = "1.0.0"
resources = []
copyright = "Copyright Umang Surana (c) 2025"
category = "Developer Tool"
short_description = "An open source alternative to Raycast, and in rust"
osx_minimum_system_version = "10.15"

[package.metadata.bundle.osx]
info_plist_path = "bundling/Info.plist"

[package.metadata.bundle.osx.info]
LSUIElement = true
NSHighResolutionCapable = true
