[toolchain]
components = ['rustfmt', 'clippy', 'rust-src', 'rust-analyzer', 'cargo']
channel = "stable"
targets = ["x86_64-apple-darwin", "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
profile = "default"
