# Things you can configure

# Full list of modifiers: https://docs.rs/global-hotkey/0.7.0/global_hotkey/hotkey/struct.Modifiers.html#impl-Modifiers
# Do note, CMD is Super on MacOS
# If you are not sure, use google or GenAI to find out.
toggle_mod = "SHIFT"

# Full list of keys: https://docs.rs/global-hotkey/0.7.0/global_hotkey/hotkey/enum.Code.html#variants
# Same things as Modifiers, google if unsure. If something should work, but isn't working, open an issue and I'll help
toggle_key = "1"
placeholder = "Oopsie Dasies"

# Buffer (all fields are optional bools)
clear_on_hide = false
clear_on_enter = true

# The search engine to use, with the default being google:
search_url = "https://google.com/search?q=%s"
# The URL should have a %s to mark where the search arguments will go

[theme]

text_color = [0.95, 0.95, 0.96]
background_color = [0.11, 0.11, 0.13]

background_opacity = 1.0

blur = false
show_icons = true
show_scroll_bar = true
