# Default Config

toggle_mod = "ALT"
toggle_key = "Space"
placeholder = "Time to be productive!"
search_url = "https://google.com/search?q=%s"

[buffer_rules]
clear_on_hide = true
clear_on_enter = true

[theme]
text_color = [0.95, 0.95, 0.96]
background_color = [0.11, 0.11, 0.13]
background_opacity = 1.0
blur = false
show_icons = true
show_scroll_bar = true
